import { Inter } from 'next/font/google'
import styles from './page.module.css';
import Link from "next/link"


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'e-Migué',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <div className={styles.barra_esquerda}>
          
            <div className={styles.rectangle_2} />

            <div>
            <Link href ='/' className={styles.login_button}>
              <img
                className={styles.sair}
                alt="Icon sair"
                src={"/Sair.png"}
              />
              </Link>
            </div>

            <div>
              <Link href ='/rota-professores' className={styles.login_button}>
              <img
                
                className={styles.icon_professor}
                alt="Icone professores"
                src={"/Professores.png"}
              />
              </Link>
            </div>
            <div>
            <Link href ='/rota-disciplinas' className={styles.login_button}>
              <img
                className={styles.icon_disciplinas}
                alt="Icone disciplinas"
                src={"/Disciplinas.png"}
              />
            </Link>  
            </div>
            <Link href ='/user' className={styles.login_button}>
              <img
                  className={styles.pgina_inicial}
                  alt="Home"                                                                                             
                  src={"/pagina_inicial.png"}
              />
            </Link>  
            </div>

          <img
            className={styles.icon_voltar}
            alt="Icon voltar"
            src="https://generation-sessions.s3.amazonaws.com/947dd278e122fe6a115d674876e525b1/img/icon-voltar.svg"
          />
    </html>
  )
}
